# Generated by Django 4.0 on 2022-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0006_remove_student_username_student_bits_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(choices=[('Rana Pratap Bhawan', 'Rana Pratap Bhawan'), ('Ashok Bhawan', 'Ashok Bhawan'), ('Bhagirath Bhawan', 'Bhagirath Bhawan'), ('Vishwakarma Bhawan', 'Vishwakarma Bhawan'), ('Krishna Bhawan', 'Krishna Bhawan'), ('Gandhi Bhawan', 'Gandhi Bhawan'), ('Shankar Bhawan', 'Shankar Bhawan'), ('Vyas Bhawan', 'Vyas Bhawan'), ('Ram Bhawan', 'Ram Bhawan'), ('Budh Bhawan', 'Budh Bhawan'), ('Meera Bhawan', 'Meera Bhawan'), ('NOT YET ALLOTED', 'NOT YET ALLOTED')], default='NOT YET ALLOTED', max_length=50),
        ),
    ]
