# Generated by Django 4.0 on 2022-01-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libmansys", "0008_requested_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requested_book",
            name="ISBN",
        ),
        migrations.AddField(
            model_name="requested_book",
            name="book",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="libmansys.book",
            ),
            preserve_default=False,
        ),
    ]
