# Generated by Django 4.0 on 2022-01-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0009_remove_requested_book_isbn_requested_book_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
