# Generated by Django 4.0 on 2022-01-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0010_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_book',
            name='issued',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='requested_book',
            name='book',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='libmansys.book'),
        ),
        migrations.AlterField(
            model_name='requested_book',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='libmansys.student'),
        ),
    ]
