# Generated by Django 4.0 on 2022-01-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0011_requested_book_issued_alter_requested_book_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requested_book',
            old_name='issued',
            new_name='issue',
        ),
    ]
