# Generated by Django 4.0 on 2022-01-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0013_requested_book_reason_alter_requested_book_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='BITS_ID',
            new_name='bits_id',
        ),
    ]
