# Generated by Django 4.0 on 2022-01-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0015_alter_student_bits_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requested_Book',
            new_name='RequestedBook',
        ),
    ]
