# Generated by Django 4.0 on 2022-01-23 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0016_rename_requested_book_requestedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_ID',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
