# Generated by Django 4.0 on 2022-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0017_alter_student_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestedBook',
            new_name='Requested_Book',
        ),
        migrations.AlterField(
            model_name='student',
            name='bits_id',
            field=models.CharField(default='NOT YET UPDATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_ID',
            field=models.IntegerField(default=-1),
        ),
    ]
