# Generated by Django 4.0 on 2022-01-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmansys', '0018_rename_requestedbook_requested_book_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requested_Book',
            new_name='RequestedBook',
        ),
    ]
